version: '3.8'

services:
  xlxd:
    container_name: xlxd
    hostname: xlxd
    image: cbodden/xlxd-docker:latest
    restart: unless-stopped
    environment:
      - CALLHOME='false'
      - CALLSIGN='XYZ123'
      - COMMENT='Hosted by XYZ123'
      - COUNTRY='United States'
      - DESCRIPTION='XLX000 by XYZ123'
      - EMAIL='me@email.com'
      - MODULES='4'
      - MODULEA='Int.'
      - MODULEB='Regional'
      - MODULEC='National'
      - MODULED=''
      - PORT='80'
      - TZ='UTC'
      - URL='site.web.com'
      - XLXNUM='XLX000'
    ports:
      - 80:80/tcp       # The www port
      - 8080:8080/udp   # repnet
      - 8880:8880/udp   # dmr
      - 10001:10001/udp # xlxcore
      - 10002:10002/udp # xlx interlink
      - 12345:12345/udp # icom terminal 1
      - 12346:12346/udp # icom terminal 2
      - 20001:20001/udp # dplus
      - 21110:21110/udp # yaesu imrs
      - 30001:30001/udp # dextra
      - 30051:30051/udp # dcs
      - 40000:40000/udp # icom dv
      - 42000:42000/udp # ysf
      - 62030:62030/udp # mmdvm
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
